# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'analytics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for analytics
  pod 'Analytics', '~> 3.0'

  target 'analytics-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'analyticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
